name: Deploy Hugo pages

on:
  push:
  schedule:
    - cron: 0 0 * * *
      timezone: America/New_York

jobs:
  call:
    name: Call workflow
    uses: Anthrocon/actions-pages/.github/workflows/deploy.yaml@7aa77de621f74c2d1c273a1a6d694b3cebb664f7
    with:
      cloudflare-project: anthrocon
      cloudflare-project-create: true
      hugo-version: 0.164.0

    secrets:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
